### ISSUE TITLE
0 flag and pass fail status. 

### ISSUE THREAD

**Issue by alquesadilla** [exussum12/coverageChecker#19]
So I tested this a bit more and this is what I found.

If you use a 0 on the command line to not trigger the failure you get an output of status 'Passed' even though there were violations found. See output below:

```php
stdClass Object
(
    [coverage] => 20.00
    [status] => Passed
    [violations] => stdClass Object
        (
            [app/Http/Controllers/CountyController.php] => Array
                (
                    [0] => stdClass Object
                        (
                            [lineNumber] => 27
                            [message] => Array
                                (
                                    [0] => Expected 1 space between comma and argument "$state"; 0 found
                                )

                        )

                )

            [app/Http/Controllers/PaymentController.php] => Array
                (
                    [0] => stdClass Object
                        (
                            [lineNumber] => 31
                            [message] => Array
                                (
                                    [0] => Expected 1 space after comma in function call; 2 found
                                )

                        )

                )

        )

)
```

When I don't use the 0,  and using the  --report=json flag, I get:

```php
**Failing due to coverage being lower than threshold**
stdClass Object
(
    [coverage] => 20.00
    [status] => Failed
    [violations] => stdClass Object
        (
            [app/Http/Controllers/CountyController.php] => Array
                (
                    [0] => stdClass Object
                        (
                            [lineNumber] => 27
                            [message] => Array
                                (
                                    [0] => Expected 1 space between comma and argument "$state"; 0 found
                                )

                        )

                )

            [app/Http/Controllers/PaymentController.php] => Array
                (
                    [0] => stdClass Object
                        (
                            [lineNumber] => 31
                            [message] => Array
                                (
                                    [0] => Expected 1 space after comma in function call; 2 found
                                )

                        )

                )

        )

)
```

notice the output at the top 'Failing due to coverage being lower than threshold' shows up.   Ideally it would be nice if one can still pass 0 on the command line. And get similar pass/fail status so that you don't have to worry about the 'Failing due to coverage being lower than threshold' message.   What do you think?

**Comment by alquesadilla** [comment]
The problem is that I always get 'Failed' from diffFilter if I don't use 0 even if phpcs has no violations.

 if I use 0 then it respects the fact that no violations were found on clean files but on phpcs violation files it doesn't find it. Its definitely buggy. 


In summary I can't use it with 0 or without 0. 


Sorry I know Im being taxing to you.

**Comment by alquesadilla** [comment]
I guess I could just do a test on count of violations. If count(violations) > 0 then its a fail. Just wanted to point it out to you.

**Comment by exussum12** [comment]
The passed flag is basically is the number from report higher than the one you will accept.

If your passing 0 in it means this will always be Passed.

There was a bug with the flag for = to, this was fixed in master but not yet tagged, I have a few other changes going in. This will be tagged as 0.7.1 tomorrow.

**Comment by exussum12** [comment]
0.7.1 fixes the status flag issue.
