### ISSUE TITLE
Would it be possible to get a PHAR?

### ISSUE THREAD

**Issue by heiglandreas** [exussum12/coverageChecker#28]
Hey Scott. Looks exactly like a tool I was looking for for some time. *But*: I'd rather use it as phar-file so that it doesn't break my dependencies when running `composer install`.

Would it be possible to get one?

I'd be happy to provide ideas on how to automate that ;)

**Comment by exussum12** [comment]
I will take a look at getting this sorted. I will also have a look at shifting some dependencies in my composer install

**Comment by exussum12** [comment]
I have attached the phar file here

https://github.com/exussum12/coverageChecker/releases/tag/v0.8.0

A quick test looks ok - let me know if it works!

**Comment by exussum12** [comment]
I have just out the PR up too, Would you mind taking a look ?

**Comment by exussum12** [comment]
Closing, The phar file appears to work, re open if you have any issues with it
