### ISSUE TITLE
Class 'PhpParser\ParserFactory' not found

### ISSUE THREAD

**Issue by gpressutto5** [exussum12/coverageChecker#33]
This problem came with PhpParser after #30.

[My script](https://github.com/ebanx/woocommerce-gateway-ebanx/blob/master/.scripts/phpcs.sh)
[Broken build](https://travis-ci.org/ebanx/woocommerce-gateway-ebanx/builds/341891192?utm_source=github_status&utm_medium=notification)

**Comment by exussum12** [comment]
I will take a look thanks, I haven't tagged this  version yet as I was still doing further testing, Would it be possible to update your composer to not use dev-master and use ^0.8.0 instead ?

**Comment by exussum12** [comment]
As an update, I have reproduced this locally, Thanks for the in depth info in this report!

**Comment by exussum12** [comment]
Fix merged to master. Thanks for the report. I will tag this version now, Thanks!

**Comment by exussum12** [comment]
Tagged the fix (0.9.0) Thanks again for the report :)
