### ISSUE TITLE
PHAR has issues with path

### ISSUE THREAD

**Issue by heiglandreas** [exussum12/coverageChecker#43]
When I download the PHAR-file and rename it from `diffFilter.phar` to something else like `diffFilter` (note the missing `.phar`) I am not able to use it any more due to the following error:

```bash
    PHP Warning:  require(phar://diffFilter.phar/src/Runners/generic.php): failed to open stream: phar error: invalid url or non-existent phar "phar://diffFilter.phar/src/Runners/generic.php" in /path/to/diffFilter on line 3
PHP Stack trace:
PHP   1. {main}() /path/to/diffFilter:0

Warning: require(phar://diffFilter.phar/src/Runners/generic.php): failed to open stream: phar error: invalid url or non-existent phar "phar://diffFilter.phar/src/Runners/generic.php" in /path/to/diffFilter on line 3

Call Stack:
    0.0014     394744   1. {main}() /path/to/diffFilter:0

PHP Fatal error:  require(): Failed opening required 'phar://diffFilter.phar/src/Runners/generic.php' (include_path='.:/usr/local/Cellar/php/7.2.3_2/share/pear') in /path/to/diffFilter on line 3
PHP Stack trace:
PHP   1. {main}() /path/to/diffFilter:0

Fatal error: require(): Failed opening required 'phar://diffFilter.phar/src/Runners/generic.php' (include_path='.:/usr/local/Cellar/php/7.2.3_2/share/pear') in /path/to/diffFilter on line 3

Call Stack:
    0.0014     394744   1. {main}() /path/to/diffFilter:0
```

Renaming the file back to `diffFilter.phar` causes the error to disappear. 

Why is that an issue? I'm usually installing such PHARs without the .phar-extension and call them like any unix-tool…

**Comment by exussum12** [comment]
I will take a look. This is the first phar I have made so may have missed something obvious. Thanks :)

**Comment by exussum12** [comment]
Found the issue, Just going to test the fix. I dont run 

http://php.net/manual/en/phar.mapphar.php

**Comment by exussum12** [comment]
Thanks for letting me know. I have created a new release with a phar which can be renamed.

**Comment by heiglandreas** [comment]
Thanks @exussum12 ! 👍 

Why github thought it would be cool to **not** notify me of your updates eludes me for the moment though…  😉
