### ISSUE TITLE
DiffFilter for code coverage should exclude untracked lines when running phpunit with code coverage.

### ISSUE THREAD

**Issue by chalbert-edr** [exussum12/coverageChecker#50]
Specifically, if changes to comments are made or lines are added, this would come up in the diff. When we compare this diff with the results of the coverage report, comments come up as failures.

**Comment by exussum12** [comment]
Have you got an example of this ? 

Would you mind sending me the diff and the clover file ?

Few questions also

What driver are you using for phpunit ? Xdebug or phpdbg 

What version of that driver ? 

Thanks

**Comment by chalbert-edr** [comment]
My mistake. It wasn't comments, but parentheses rather. This may not be an actual issue, but it would be nice if I could exclude these. I'm running php7.0.22 with xDebugv2.4.0. I'm sorry, but that's all I can provide. If interested I can generated this on a public codebase for an example.

![image](https://user-images.githubusercontent.com/30605766/46901350-d84ea000-ce7f-11e8-8fe8-a2b9916d6e59.png)

![image](https://user-images.githubusercontent.com/30605766/46901356-f0beba80-ce7f-11e8-8a71-45042b6d556d.png)

**Comment by exussum12** [comment]
These should be excluded. Only actual code changes should be.

I've seen this happen previously when the build runs and merges another branch (you can normally see this at the top of the build output). If that is the case. The diff file will be outdated which can cause this. 

A public example would be great 

Thanks

**Comment by exussum12** [comment]
If that is the case git diff origin/master should work fine after the merge has taken place.

That should hopefully sync the lines and not show that as an issue

**Comment by exussum12** [comment]
@chalbert-edr  any luck with the above ?

**Comment by chalbert-edr** [comment]
Thank you for following up, @exussum12.  Since you had seen the issue, I spent some time this weekend trying to diff against origin/master after the commits were merged - still no luck. Let me try with a public repo...results coming over shortly.

**Comment by chalbert-edr** [comment]
@exussum12 I'm having issues recreating the problem in another repo. I think this one may be on me :) Thank you for the prompt attention though. Great library!

**Comment by exussum12** [comment]
That's for using :) 

Feel free to email me the two files if you come across it again I will take a look
