### ISSUE TITLE
git merge-base is missing an argument

### ISSUE THREAD

**Issue by andreasciamanna** [exussum12/coverageChecker#58]
In the documentation, the recommended approach for building a diff file is to use `git diff $(git merge-base origin/master...HEAD)`.

However, `git merge-base origin/master...HEAD` is missing an argument and always displays a usage helper.

I'm not familiar with `git merge-base` and I couldn't figure how to make it right.

Like in the example, I'm trying to do build the diff file so that it works both locally and in the CI.

In the CI, I will replace `master` with the actual target branch (from a GitLab environment variable called `CI_MERGE_REQUEST_TARGET_BRANCH_NAME`).

Any advice?

**Comment by exussum12** [comment]
Sorry it should be missing the three dots. 

git merge-base origin/master HEAD
Or in your case you could also use

git diff ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}...HEAD

That should be the short hand syntax for the diff 

I'll update docs tomorrow thanks for reporting this :)

**Comment by andreasciamanna** [comment]
Thanks!
