### ISSUE TITLE
Release a new version to address PHP 7.4 issue

### ISSUE THREAD

**Issue by htdat** [exussum12/coverageChecker#66]
Hi 👋, 

We're seeing this error with ver 0.11.2 with PHP 8.0, which was released on 2019-04-17 (also the latest version for now).

> PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/runner/work/Edit-Flow/Edit-Flow/vendor/exussum12/coverage-checker/src/ArgParser.php on line 25

Our test is here https://github.com/Automattic/Edit-Flow/runs/2407816247?check_suite_focus=true

I see that this error was fixed on https://github.com/exussum12/coverageChecker/commit/b5c7b7f98afc45c9da8c8f47f62dd22195660d7c

But there is no release for it. Could you consider releasing it? 

Thanks in advance.

**Comment by exussum12** [comment]
v1.0.0 tagged - if your using the binary nothing should change, if you depend on internal classes some the the structure has changed

**Comment by htdat** [comment]
Great! Thank you a lot.
