### ISSUE TITLE
compatibility with phpunit ^9.*

### ISSUE THREAD

**Issue by nockschii** [exussum12/coverageChecker#68]
Hello,

my team and I have used this package to check uncovered classes. Now with phpunit 9, it isn't correctly anymore.
Can we expect a future update?

**Comment by tippold** [comment]
I have the same problem. Not working with phpunit 9. An update would be greatly appreciated.

**Comment by exussum12** [comment]
What issues are you getting with phpunit 9 ? 1.0 should have resolved any of them.

If it has not can you post a resproduacble case and I will resolve it ,:)

**Comment by exussum12** [comment]
Sorry the phpunit 9 bit was not tagged, I have just tagged 1.0.1 please use that :)

**Comment by tippold** [comment]
Thank you very much! That did the trick :)

**Comment by nockschii** [comment]
For me too. Thanks alot!
